// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yluhgcbluxsnzlyhyabr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsdWhnY2JsdXhzbnpseWh5YWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDc1NTksImV4cCI6MjA2MDg4MzU1OX0.1_N6VVz_XS7bOALgmhbiTSGzCK9_F5ChkUQ_lKVBpY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);